### ISSUE TITLE
Fix indices order in read and write of the color matrix used to produce wavescapes

### ISSUE THREAD

**Issue by cedricviaccoz** [DCMLab/wavescapes#12]
Issues spotted by @johentsch , in some parts of the code the Y and X axis are inverted to read and write colors in the matrix (examples [here ](https://github.com/DCMLab/wavescapes/blob/8203b6613ef32d9e5efa78cdaab73f05ad64558b/wavescapes/color.py#L192) and [here ](https://github.com/DCMLab/wavescapes/blob/8203b6613ef32d9e5efa78cdaab73f05ad64558b/wavescapes/draw.py#L262)). The inversion of those access indices are consistent along the whole library, so it does not cause any issue in the visualisation, but it sure does confuse code readers.

**Comment by johentsch** [comment]
Thanks for writing the issue, @cedricviaccoz . Here's an example that clarifies the confusion. It is simply the DFT of the chromatic scale, generated by rotating the array.
![image](https://user-images.githubusercontent.com/42718519/150808385-c4ac00fe-202b-4371-9fb2-cbdae7aeea9f.png)

```python
>>> import wavescapes
>>> import numpy as np
>>> single_pitch = np.array([1,0,0,0,0,0,0,0,0,0,0,0])
>>> transpositions = np.array([np.roll(single_pitch, i) for i in range(12)])
>>> dft = wavescapes.apply_dft_to_pitch_class_matrix(transpositions)
>>> np.array([[abs(coeff) for coeff in dft[0][j]] for j in range(12)])
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])
>>> np.array([[abs(coeff) for coeff in dft[j][j]] for j in range(12)])
array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 1.93185165e+00, 1.73205081e+00, 1.41421356e+00,
        1.00000000e+00, 5.17638090e-01, 1.24126708e-16],
       [3.00000000e+00, 2.73205081e+00, 2.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 7.32050808e-01, 1.00000000e+00],
       [4.00000000e+00, 3.34606521e+00, 1.73205081e+00, 0.00000000e+00,
        1.00000000e+00, 8.96575472e-01, 1.11022302e-16],
       [5.00000000e+00, 3.73205081e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 2.67949192e-01, 1.00000000e+00],
       [6.00000000e+00, 3.86370331e+00, 0.00000000e+00, 1.41421356e+00,
        0.00000000e+00, 1.03527618e+00, 0.00000000e+00],
       [7.00000000e+00, 3.73205081e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 2.67949192e-01, 1.00000000e+00],
       [8.00000000e+00, 3.34606521e+00, 1.73205081e+00, 0.00000000e+00,
        1.00000000e+00, 8.96575472e-01, 1.24126708e-16],
       [9.00000000e+00, 2.73205081e+00, 2.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 7.32050808e-01, 1.00000000e+00],
       [1.00000000e+01, 1.93185165e+00, 1.73205081e+00, 1.41421356e+00,
        1.00000000e+00, 5.17638090e-01, 1.11022302e-16],
       [1.10000000e+01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.20000000e+01, 2.77555756e-16, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])
```

Intuitively, I would have expected the exact inverse output for the last two lines: fixing `x=0` should yield values for the intervals `(0, 0), (0, 1) ...` (i.e. element 0 should increase from 1 to 12); whereas equal indices should yield intervals of same length `(0, 0), (1,1) ...` and therefore identical coefficients (due to transpositional invariance in this example).

**Comment by cedricviaccoz** [comment]
Thanks for the detailed use case. 

For the warnings, I'd say try to update your matplotlib installation ( `pip install --upgrade matplotlib` ), it seems the warning stems from your local configuration of matplotlib rather than its use within the wavescapes library. 

However if you can confidently say the warning are an issue with how matplotlib is used in my code, I'd suggest you open up a dedicated new Issue on the subject.

**Comment by johentsch** [comment]
matplotlib warnings keep appearing with the latest version of matplotlib. Created #14

**Comment by johentsch** [comment]
I've gained some insight into the indexing and a reason why you might want to leave it as it is.

**Desired**

Let's say `M[i, j]` means "give me the segment that starts at `i` and ends with `j`(inclusively). The length of the requested segment is `n = j-i` (upper triangle: `j>=i`).

**Currently**

Your matrices hold values with indexing format `M[n, j]`, in other words, "give me the segment of length `n` that ends with `j`. This probably makes sense when using nested for-loops because the first row to be written is the bottom of the wavescape, i.e. the segments with `n=0`: (0,0), (1,1) etc., that's why they get the coordinates (0,0), (0, 1), etc.

**Solution**

When passed `i` and `j`, before retrieving a value, turn `i` into `n`: `n = j-i`.

Having understood this, I would argue that you don't need to change any code, except for renaming the variables `x` and `y` in the nested for-loops to something that avoids this misunderstanding.

P.S.: An upper-triangle matrix can flipped like this:

```python
def flip_utm(utm):
    n, j = np.triu_indices(utm.shape[0])
    utm[n, j] = utm[j-n,j]
    return utm
```
